version: '3.7'

services:
  mongo:
    image: mongo:3.4.19-jessie
    container_name: awesome-mongo
    ports:
      - 27017:27017
    volumes:
      - ./database/data/db:/data/db

  backend:
    build: ./backend
    image: hiper2d/awesome-dice-backend
    container_name: awesome-backend
    ports:
      - 8080:8080
    volumes:
      - ./logs:/logs
    entrypoint: /opt/backend/bin/entrypoint.sh
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    image: hiper2d/awesome-dice-frontend
    container_name: awesome-frontend
    ports:
      - 80:80
    depends_on:
      - backend
