jwt:
  header: Authorization
  secret: awesome
  prefix: bearer

spring.data.mongodb.uri: mongodb://awesome-mongo:27017/test

---
spring:
  profiles: local

  data.mongodb.uri: mongodb://localhost:27017/test
